name: epson_epos
description: This plugin allows Flutter apps to discover printers and send data to EPSON ePOS.
version: 0.0.2
repository: https://github.com/ImTung/flutter_epson_epos
homepage: https://github.com/ImTung/flutter_epson_epos

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.tlt.epson_epos
        pluginClass: EpsonEposPlugin
      ios:
        pluginClass: EpsonEposPlugin
